# Python Object Oriented Programming

This is a tutorial on basic Python syntax and concepts for the [KIPAC computing boot camp](http://kipac.github.io/BootCamp).

Author: [Sean McLaughlin](https://github.com/mclaughlin6464)

Object Oriented Programming (OOP) is arguably the most popular programming paradigm. It refers to a "style" of programming, partly in the user's control and partly emphasized by the programming language itself. Python, for example, was built from the start as an OOP language. That means that much of the language's built-ins follow and OOP design, and making your own objects is easy. 

**Disclaimer:** OOP is a powerful and popular programming paradigm. It is not, however, the only one. Some people have very, *very* strong opinions on this. For the next hour, we'll ignore those people. However, keep in mind going forward there are other was to design a program, and OOP is not always the best way! 

# TODO DELETME
Topics to cover:
* Iheritance
* Abstract classes

-----
### Part 0: What is OOP?

What *is* an object?

Well, first what *is* programming? 

Programming, in the most abstract sense, is defining logic to perform manipulations on data. 

An object is an abstract... um... *object* that contains both its relevant data and functions to manipulate that data. It follows from the idea that what we really care about are these abstract objects than the logic or data separately. 

Ok sure but... what *is* an object?

It can be a lot of things. It can represent something real, like a student or an astronomical object. It can represent something more abstract, like a statistical model or a cosmology. It could even be something completely abstract. For example, all the widgets and cells in this notebook are actually objects within the Jupyter code. 


Programming with objects allows you to design your programs the way you actually understand the logic yourself. 

---
### Part 1: Python Classes 

Let's make a simple class to get started. 

In [1]:
class Student(object):
    'A class defining a student!'
    
    def __init__(self, name, gpa, major = 'Physics'):
        '''
        Initialize the student. 
        
        name: String, the student's name
        gpa: The student's overall gpa
        major: The student's major. Default is Physics. 
        '''
        self.name = name
        self.gpa = gpa
        self.major = major
        
    def change_major(self, new_major):
        '''
        Change the student's major. 
        
        new_major: str, the student's new major
        '''
        if new_major != self.major:
            self.major=new_major
        else:
            print "%s is already %s's major!"%(self.major, self.name)
        

There's a lot to unpack here, so lets break it down. We've defined a class `Student` that has three attributes and two methods.

The attributes are:
* name
* gpa
* major

And the methods are:
* \__init__
* change_major

How do these work? Let's make some instances to see. 

In [17]:
student1 = Student('Sean', 3.0)
print type(student1)
print student1.name, student1.gpa, student1.major
student2 = Student('Alice', 4.5, major='Biology')

student2.change_major('Physics')#she wised up
student1.change_major('Physics')#this should print! 
print student1.__doc__ #access the docstring

<class '__main__.Student'>
Sean 3.0 Physics
Physics is already Sean's major!
A class defining a student!


There's a few things to notice here:
* student1 and student2 are *instances* of the student object. 
* We can access a Student's attributes and methods via `.` syntax
* The \__init\__ method is what is called the *constructor*. It details the initialization of the instance. 
* Both methods have *self* as their first argument, but it is not passed in when called. This is how class methods are defined, and allows them to access the object's attributes.
* Pay close attention to how the `Student` object is declared. It *inherits* from the `object` class. We'll discuss what that means in more detail later, but it is not exactly necessary to do that. It is, however, strongly encouraged. 

In [3]:
class Student2:
    'A class defining a student!'
    
    def __init__(self, name, gpa, major = 'Physics'):
        '''
        Initialize the student. 
        
        name: String, the student's name
        gpa: The student's overall gpa
        major: The student's major. Default is Physics. 
        '''
        self.name = name
        self.gpa = gpa
        self.major = major
        
    def change_major(self, new_major):
        '''
        Change the student's major. 
        
        new_major: str, the student's new major
        '''
        if new_major != self.major:
            self.major=new_major
        else:
            print "%s is already %s's major!"%(self.major, self.name)
        

In [4]:
#run the same code without inheriting from object
student1 = Student2('Sean', 3.0)
print student1.name, student1.gpa, student1.major
student2 = Student2('Alice', 4.5, major='Biology')

student2.change_major('Physics')#she wised up
student1.change_major('Physics')#this should print! 
print student1.__doc__ #access the docstring

Sean 3.0 Physics
Physics is already Sean's major!
A class defining a student!


Python 2 supports these "old style classes" for backward compatibility reasons, but Python 3 does not. They function the same way in a number of ways, but they differ in subtle ways; just use new style classes! You can read more about the details [here](https://wiki.python.org/moin/NewClassVsClassicClass). 

---
### Excercise 1
#### Answers Below
Define a class named `Professor` with the following attributes:
* A name attribute
* An integer attribute `n_papers`
* A boolean attribute `tenure` that defaults to `False`.

And the following methods:
* An `__init__` method that initializes the attributes
* A `write_paper` method that increments `n_papers` by one. 
* A `check_tenure` method that sets `tenure` to true if `n_papers` is greater than 10. 

Make sure to test it out! 

---
### Part 2: More Complex Objects and Operator Overloading

Below I've defined a more complex object than the one above; take some time to read and understand it. What are its attributes and methods?

In [5]:
from math import pi
class Planet(object):
    'A class defining the attributes of a planet.'
    
    G = 6.67e-11 #Newton's constant in SI units
    
    def __init__(self,name, order, mass,radius, moons=[]):
        '''
        Initialize the planet object.
        name: str, the name of the planet
        order: int, the planet's order in distance from the sun. 
        mass: float, The mass of the planet (in kg)
        radius: float, radius of the planet (in m)
        moons: list, a list of the names of the planet's moons. Default is an empty list. 
        '''
        self.name = name
        self.order = order
        self.mass = mass
        self.radius = radius
        self.moons=moons
        
        volume = 4/3*pi*self.radius**3#volume is not stored
        self._density = self.mass/volume
        
    def __cmp__(self, other):
        '''
        Define comparison between planets. Defined as the planet closer to the sun is "less"
        
        other: Another Planet object
        
        return: the difference of self and other's orders. 
        '''
        return self.order-other.order
    
    def __str__(self):
        return self.name

    def num_moons(self):
        '''
        Return the number of moons the planet has
        
        return: Int, the number of moons
        '''
        return len(self.moons)
    
    def gravity(self, r):
        '''
        Calculate the acceleration due to gravity of the planet at a distance r.
        r: float, the distance from the planet's center to calculate the force of gravity.
        
        return: float, the strength of gravity in m/s^2
        '''
        return self.G*self.mass/(r*r)
    
    def surface_gravity(self):
        '''
        Calculate the acceleration due to gravity on the planet's surface. 
        
        return: float, the surface gravity in m/s^2
        '''
        return self.gravity(self.radius)

This object has quite a bit more instances and methods. Some of which are easier to understand, like we used above. 

In [6]:
earth = Planet('Earth', 3, 5.972e24, 6.371e6, moons=['Luna'])
print earth.num_moons()
print earth.G
print earth.surface_gravity()
print earth.gravity(1e7)

1
6.67e-11
9.81364678737
3.983324


Most of that we've seen above, but what is `G`?. `G` is an example of a class variable; instead of being attached to an individual object it is attached to the class. 

All instances carry the same value of `G`. Note that if one instances class variable is modified, it does not change the other instances. And if we change it for the class, they do for new objects and those which have not already been changed! . It can be tough to keep track of, so it's not reccomended to modify these. 

In [7]:
mars = Planet('Mars', 4, 6.39e23, 3.39e6, moons=['Phobos', 'Deimos'] )
print mars.G, earth.G, Planet.G
mars.G = 1 #change for instance
print mars.G, earth.G, Planet.G

Planet.G = 0
print mars.G, earth.G, Planet.G

mars = Planet('Mars', 4, 6.39e23, 3.39e6, moons=['Phobos', 'Deimos'] )
print mars.G, earth.G, Planet.G

6.67e-11 6.67e-11 6.67e-11
1 6.67e-11 6.67e-11
1 0 0
0 0 0


In [9]:
#fix things. 
Planet.G=6.67e-11
mars = Planet('Mars', 4, 6.39e23, 3.39e6, moons=['Phobos', 'Deimos'] )
earth = Planet('Earth', 3, 5.972e24, 6.371e6, moons=['Luna'])
print mars.G, earth.G, Planet.G

6.67e-11 6.67e-11 6.67e-11


Also notice that 
* The variable `volume` is not stored as an instance variable, so it can't be accessed. 
* The variable `_density` has one underscore. The one underscore symbolizes that the object should be treated as "private", but that is not enforced. If it had been named `__density`, the behavior would've been different. If you're interested in the way python sort of does private variables, read about [name mangling](https://en.wikipedia.org/wiki/Name_mangling#Python). 
* The method `surface_gravity` makes use of the instance method `gravity`; in fact it's a special case of that broader function. 

There is an elephant in the room, though. What about the `__*__` methods? That is the syntax for python's "special" or "magic" methods. They have defined behavior, and they can be used in your own objects. Let's take a look at how these methods work:

In [13]:
print str(earth), str(mars)# call __str__

print earth.__str__(), mars.__str__()

Earth Mars
Earth Mars


In [16]:
print earth > mars # call __cmp__
print 0 < earth.__cmp__(mars) 

False
False


What do we see here? These built-in functions and operations actually just call these "magic" methods!

So overloading those operations allows you to define how those objects work with operations like these. This is operator overloading. You should skim all the ones that are available [here](https://docs.python.org/2/reference/datamodel.html)

---
### Aside

This "operator overloading" is not just for user-defined objects. It is used in major third party packages and is essential to python itself. Take, for example, numpy's exceptionally powerful array object.

In [12]:
import numpy as np
x = np.array(range(5))
print x
print x+1 #overload __add__
x+=10 #overload __iadd__
print x
print x>5 #overload __cmp__
x = np.array(range(5))
y = np.array(range(5,10))
print x+y #overload __add__ with an alternative behavior

[0 1 2 3 4]
[1 2 3 4 5]
[10 11 12 13 14]
[ True  True  True  True  True]
[ 5  7  9 11 13]


What about these operations in python? Well this allows us to really peer under the hood of python.

In [22]:
x = 1
y= x.__add__(1)
print y
z = range(10)
print z.__len__()

2
10


This is how python objects work too! In python, everything is an object, and the objects you create are not that different than the built-ins! 

---
### Excercise 2
#### Answers Below

Define a new class Professor2. It should have all the same instance variables as Professor. However:
* redefine the `__iadd__` magic method to add to `n_papers` the value on the right and return self
* overload the `__nonzero__` (similar to `bool`) method to have the same functionality as `check_tenure` and return `self.tenure`

Write it below, and then run the cell below (and make sure it works!). 

In [ ]:
prof = Professor2('Jim', 0)
whlie not prof:
    print prof.n_papers
    prof+=1

## Answers

In [13]:
#Excercise 1
class Professor(object):
    'A professor on a surprisngly easy tenure track.'
    
    def __init__(self,name, n_papers, tenure=False ):
        'Initialize the professor.'
        self.name = name
        self.n_papers = n_papers
        self.tenure=tenure
        
    def write_paper(self):
        self.n_papers+=1
        
    def check_tenure(self):
        self.tenure = self.n_papers > 10

In [16]:
prof = Professor('Jim', 0)
#Academia, in a nutshell
while not prof.tenure:
    print prof.n_papers
    prof.write_paper()
    prof.check_tenure()

0
1
2
3
4
5
6
7
8
9
10


In [39]:
#Excercise 2
class Professor2(object):
    'A professor on a surprisngly easy tenure track.'
    
    def __init__(self,name, n_papers, tenure=False ):
        'Initialize the professor.'
        self.name = name
        self.n_papers = n_papers
        self.tenure=tenure
        
    def __iadd__(self, other):
        self.n_papers+=other
        return self
        
    def __nonzero__(self):
        self.tenure = self.n_papers > 10
        return self.tenure

In [40]:
prof = Professor2('Jim', 0)
while not prof:
    print prof.n_papers
    prof+=1

0
1
2
3
4
5
6
7
8
9
10
