# Python: numpy, and matplotlib

This is a tutorial on scientific Python for the [KIPAC computing boot camp](http://kipac.github.io/BootCamp).

Authors: [Yao-Yuan Mao](http://yymao.github.io), [Joe DeRose](https://github.com/j-dr)

In [25]:
from __future__ import print_function, division
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from IPython.display import display

Numpy and matplotlib are the workhorse packages of the scientist using python. Efficient use of numpy is the only way to perform most operations in a tractable amount of time in python. Once you've performed those operations, matplotlib is the go to package for visualization.

## numpy
Why use numpy instead of regular old python?

**python** has built-in:   
containers: lists (costless insertion and append), dictionnaries (fast lookup)    
high-level number objects: integers, floating point


**numpy** is:   
an extension package to Python for multidimensional arrays   
closer to hardware (efficiency)   
designed for scientific computation (convenience)   


### Creating arrays
The fundamental object in numpy is the ndarray. Here we will see how to create them.

In [38]:
#an array of all zeros (pass in the shape of the array you want)
shape = (10,10)
z = np.ndarray(shape)
print('The shape of this array is {0}'.format(z.shape))
display(z)

The shape of this array is (10, 10)


array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [39]:
#an array of zeros
z = np.zeros(shape)
display(z)
o = np.zeros(shape)
display(o)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [27]:
#A range of integers
a = np.arange(100)
display(a)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [44]:
#An array with numbers at linearly spaced intervals
l = np.linspace(0,5,100)
display(l)

array([ 0.        ,  0.05050505,  0.1010101 ,  0.15151515,  0.2020202 ,
        0.25252525,  0.3030303 ,  0.35353535,  0.4040404 ,  0.45454545,
        0.50505051,  0.55555556,  0.60606061,  0.65656566,  0.70707071,
        0.75757576,  0.80808081,  0.85858586,  0.90909091,  0.95959596,
        1.01010101,  1.06060606,  1.11111111,  1.16161616,  1.21212121,
        1.26262626,  1.31313131,  1.36363636,  1.41414141,  1.46464646,
        1.51515152,  1.56565657,  1.61616162,  1.66666667,  1.71717172,
        1.76767677,  1.81818182,  1.86868687,  1.91919192,  1.96969697,
        2.02020202,  2.07070707,  2.12121212,  2.17171717,  2.22222222,
        2.27272727,  2.32323232,  2.37373737,  2.42424242,  2.47474747,
        2.52525253,  2.57575758,  2.62626263,  2.67676768,  2.72727273,
        2.77777778,  2.82828283,  2.87878788,  2.92929293,  2.97979798,
        3.03030303,  3.08080808,  3.13131313,  3.18181818,  3.23232323,
        3.28282828,  3.33333333,  3.38383838,  3.43434343,  3.48

In [45]:
#An array with numbers at log spaced intervals
l = np.logspace(1,5,100)
display(l)

array([  1.00000000e+01,   1.09749877e+01,   1.20450354e+01,
         1.32194115e+01,   1.45082878e+01,   1.59228279e+01,
         1.74752840e+01,   1.91791026e+01,   2.10490414e+01,
         2.31012970e+01,   2.53536449e+01,   2.78255940e+01,
         3.05385551e+01,   3.35160265e+01,   3.67837977e+01,
         4.03701726e+01,   4.43062146e+01,   4.86260158e+01,
         5.33669923e+01,   5.85702082e+01,   6.42807312e+01,
         7.05480231e+01,   7.74263683e+01,   8.49753436e+01,
         9.32603347e+01,   1.02353102e+02,   1.12332403e+02,
         1.23284674e+02,   1.35304777e+02,   1.48496826e+02,
         1.62975083e+02,   1.78864953e+02,   1.96304065e+02,
         2.15443469e+02,   2.36448941e+02,   2.59502421e+02,
         2.84803587e+02,   3.12571585e+02,   3.43046929e+02,
         3.76493581e+02,   4.13201240e+02,   4.53487851e+02,
         4.97702356e+02,   5.46227722e+02,   5.99484250e+02,
         6.57933225e+02,   7.22080902e+02,   7.92482898e+02,
         8.69749003e+02,

In [34]:
#1-d array creation from a list
l = range(100)
la = np.array(l)
print(type(l))
print(type(la))
print(l)
display(la)

<type 'list'>
<type 'numpy.ndarray'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [43]:
#2-d array creation from a list
l = [[0,1,2], [3,4,5]]
la = np.array(l)
display(la)
print(la.shape)


array([[0, 1, 2],
       [3, 4, 5]])

(2, 3)


In [42]:
#3-d array
c = np.array([[[1], [2]], [[3], [4]]])
display(c)
print(c.shape)

array([[[1],
        [2]],

       [[3],
        [4]]])

(2, 2, 1)


### Data types

In [50]:
#these are different arrays!
a = np.array([1, 2, 3])
print('This array has type {0}'.format(a.dtype))


b = np.array([1., 2., 3.])
print('This array has type {0}'.format(b.dtype))


This array has type int64
This array has type float64


Type can be specified

In [55]:
a = np.array([0.,1.,2.], dtype=int)
print(a.dtype)

#default dtype is float
a = np.zeros(2)
print(a.dtype)

int64
float64


In [57]:
#more complex dtypes can be specified as well
dt = np.dtype([('c1', np.float), ('c2', np.int), ('c3', str)])
z = np.ones(3, dtype=dt)
display(z)

array([(1.0, 1, ''), (1.0, 1, ''), (1.0, 1, '')], 
      dtype=[('c1', '<f8'), ('c2', '<i8'), ('c3', 'S')])

### Indexing and slicing

In [59]:
a = np.arange(100)
#numpy arrays are zero indexed
a[0], a[4], a[10]

(0, 4, 10)

In [66]:
#indices of multi dimensional arrays are tuples of integers
x = np.diag(np.arange(3))
display(x)
print(x[2,2])

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

2


In [67]:
#setting elements
x[2,2] = 10
print(x[2,2])

10


In [68]:
#slicing
x = np.arange(100)
x[0:10:2] #syntax is same as for lists start:stop:step

array([0, 2, 4, 6, 8])

### Fancy Indexing

In [74]:
#you can also use lists or other numpy arrays to index
x = np.arange(200)
x[[10,20,45]]

array([10, 20, 45])

In [93]:
#when indexing with arrays of ints, the output takes the shape of the index
a = np.arange(10)
idx = np.array([[3, 4], [9, 7]])
a[idx]

array([[3, 4],
       [9, 7]])

In [104]:
#we can also use boolean masks to index arrays
np.random.seed(3)
a = np.random.randint(0, 20, 15)
print(a)
print(a % 3 == 0)
mask = (a % 3 == 0)
extract_from_a = a[mask] # or,  a[a%3==0]
extract_from_a 

[10  3  8  0 19 10 11  9 10  6  0 12  7 14 17]
[False  True False  True False False False  True False  True  True  True
 False False False]


array([ 3,  0,  9,  6,  0, 12])

But indexing like this is much slower. We will see why in a moment.

### Exercise 1

In [77]:
x = np.arange(10000)

In [80]:
%timeit x[range(10000)[::100]]
%timeit x[::100]

10000 loops, best of 3: 117 µs per loop
The slowest run took 9.13 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 339 ns per loop


### Views and copying

In [82]:
fa = x[range(10000)[::100]]
sa = x[::100]

In [83]:
fa.base is x

False

In [90]:
#If an array does not own it's own data, we say it is a view of an array
sa.base is x

True

In [100]:
#for instance, transposes of arrays are actually views
sa.T.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [89]:
#if an array owns its own data, its base will be None
print(fa.base)

None


### Array operations

### manipulating arrays

### broadcasting

In [ ]:
a = np.arange(40).reshape(5, 8)
display(a)

In [ ]:
a = a + 1

In [ ]:
display(a)

In [ ]:
a += 1
display(a)

In [ ]:
b = np.arange(-1, -9, -1)
display(b)

In [ ]:
a + b

In [ ]:
c = np.array([10,20,30,40,50], dtype=np.float64)
display(c)

In [ ]:
a + c  # this would raise an error

In [ ]:
a += c[:,np.newaxis]

### reduce

In [ ]:
a.sum()

In [ ]:
a.mean()

In [ ]:
a.sum(axis=1)

In [ ]:
a.max(axis=0)

In [ ]:
np.median(a, axis=1)

In [ ]:
np.std(a, axis=0)

The first rule of numpy: **AVOID LARGE FOR LOOPS**

In [73]:
a = np.arange(1000)
%timeit a**2
%timeit [i**2 for i in a] #these yield identical answers

The slowest run took 9.42 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.73 µs per loop
1000 loops, best of 3: 290 µs per loop


### searching and sorting

## matplotlib

The easiest way to learn is to look at the [gallery](http://matplotlib.org/gallery.html)

In [ ]:
fig, axes = plt.subplots(ncols=2, nrows=2)
ax1, ax2, ax3, ax4 = axes.flat

# scatter plot (Note: `plt.scatter` doesn't use default colors)
x, y = np.random.normal(size=(2, 200))
ax1.plot(x, y, 'o')

# sinusoidal lines with colors from default color cycle
L = 2*np.pi
x = np.linspace(0, L)
ncolors = len(plt.rcParams['axes.color_cycle'])
shift = np.linspace(0, L, ncolors, endpoint=False)
for s in shift:
    ax2.plot(x, np.sin(x + s), '-')
ax2.margins(0)

# bar graphs
x = np.arange(5)
y1, y2 = np.random.randint(1, 25, size=(2, 5))
width = 0.25
ax3.bar(x, y1, width)
ax3.bar(x+width, y2, width, color=plt.rcParams['axes.color_cycle'][2])
ax3.set_xticks(x+width)
ax3.set_xticklabels(['a', 'b', 'c', 'd', 'e'])

# circles with colors from default color cycle
for color in plt.rcParams['axes.color_cycle']:
    ax4.add_patch(plt.Circle(np.random.randn(2), radius=0.3, color=color))
ax4.axis('equal')

plt.tight_layout()
plt.show()

### Tensor product

In [ ]:
a = np.arange(15).reshape(5,3)
b = np.arange(12).reshape(3,4)

display(a)
display(b)

In [ ]:
np.dot(a, b)

In [ ]:
a = np.arange(30).reshape(5,3,2)
b = np.arange(60).reshape(3,4,5)

display(a)
display(b)

In [ ]:
np.einsum('ijk,jli', a, b)

### useful functions

In [ ]:
# You can find most mathematical function. 
# For special functions, find them in `scipy.special`

x = np.linspace(0, np.pi*2, 101)
plt.plot(x, np.cos(x))
plt.plot(x, np.sin(x))

In [ ]:
# dealing with bool array

a = np.random.randint(2, size=20).astype(bool)
display(a)
display(np.count_nonzero(a))
display(np.where(a))

In [ ]:
# argsort

a = np.random.rand(10)

display(a)
display(a.argsort())

display(a[a.argsort()])

# note: to sort "in place", just do a.sort()

In [ ]:
# argmax and unravel_index

a = np.random.rand(100)
display(a.argmax())

a = np.random.rand(100, 100)
display(a.argmax())
display(np.unravel_index(a.argmax(), a.shape))

In [ ]:
# different ways to do histogram

a = np.random.rand(500)
bins = np.linspace(0, 1, 21)

display(np.bincount(np.searchsorted(bins, a)))

display(np.histogram(a, bins))

display(np.searchsorted(a, bins, sorter=a.argsort()))

### Task 

Given an 2-D int array, fill the 0th row and 0th column with 1, and the rest by the following rule:

    a[i,j] = a[i-1,j] + a[i,j-1]

In [ ]:
# run this cell to see hints

hint = 'Pqv|{B\x125(_wzs(wv(wvm(zw\x7f(i|(i(|qum6(\x125(aw}/tt(vmml(i(v}ux\x81(n}vk|qwv6(Vw|({}zm(\x7fpqkp(wvmG(\\z\x81(z}v(hvx6twwsnwz0/k}u}ti|q~m/1h6'
print((np.array(map(ord, hint), np.int8)-8).tostring())

In [ ]:
np.lookfor('cumulative')

In [ ]:
a = np.zeros((6, 6), int)

for i, row in enumerate(a):
    if i ==0 :
        row[:] = 1
    else:
        row[:] = np.cumsum(a[i-1])

In [ ]:
# iterate over elements
for e in a.flat:
    print e